apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 2  # Adjust the number of replicas as per your requirements
  selector:
    matchLabels:
      app: tomcat
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: ahussain900/simple-webapp:latest  # Replace with your Docker image URL
          ports:
            - containerPort: 8080  # Port that your Tomcat application listens on
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: LoadBalancer
  selector:
    app: tomcat
  ports:
    - name: http 
      protocol: TCP
      port: 8080  # External port to access the service
      targetPort: 8080  # Port that the service forwards to on the pods
